/* SECUENCIAS PARA LOS IDENTIFICADORES DE TABLAS*/

CREATE SEQUENCE SOCIOS_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
CREATE SEQUENCE SOCIOS_DOMICILIO_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
CREATE SEQUENCE CARDIO_ADICIONAL_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
CREATE SEQUENCE SOCIOS_CARDIO_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
CREATE SEQUENCE PAGO_CHQ_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
CREATE SEQUENCE PAGO_ING_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
CREATE SEQUENCE SALIDA_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;